# Generated by Django 5.1.2 on 2024-11-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='modelo_3d',
            field=models.FileField(blank=True, null=True, upload_to='modelos_3d/', verbose_name='Modelo 3D (glTF)'),
        ),
    ]
